### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by nick-telsan** [nick-telsan/tidsskrift#3]
# Rebrand

The time has come for a fresh look for `tidsskrift`. I want to match the general vibe of my personal rebrand to `evergrown`.

## Acceptance Criteria
- [ ] Overview design. Basically, what should the site look like.
- [ ] Tech stack decision. Likely React / Node for speed. Restful API w/ Prisma and NoSQL db.
- [ ] Screen. What basic screens do we want?
- [ ] Content layouts. What should our basic screens look like?

## Related Issues
