### ISSUE TITLE
Rebrand -> Design Overview

### ISSUE THREAD

**Issue by nick-telsan** [nick-telsan/tidsskrift#4]
# Rebrand -> Design Overview
> Epic: #3 

## Acceptance Criteria
- [ ] Color palette
- [ ] Logo
- [ ] General style rules
  - [ ] Fonts and Typography
  - [ ] Border radius and shadow rules
  - [ ] Buttons and interactables
